version: 2.1
orbs:
  slack: circleci/slack@3.4.2
workflows:
  version: 2
  build:
    jobs:
    - build
jobs:
  build:
    docker:
      - image: cimg/base:edge-20.04
    resource_class: xlarge
    steps:
      - checkout
      - restore_cache:
          keys:
            - csvs-{{ checksum "csvs/o1k.sha1" }}
      - run:
          name: Load test data
          command: |
            cd csvs/
            sha1sum -c o1k.sha1 || ( wget "https://www.dropbox.com/s/sgrwihjji551teq/o1k.zip?dl=1" -O temp.zip && unzip -o temp.zip && rm temp.zip && sha1sum -c o1k.sha1 )
      - save_cache:
          key: csvs-{{ checksum "csvs/o1k.sha1" }}
          paths:
            - csvs
      - run: sudo apt update && sudo apt install cmake g++
      - run: git clone --depth 1 --branch v4.0.0draft5 https://github.com/DrTimothyAldenDavis/GraphBLAS && cd GraphBLAS/build && cmake .. -DGB_BURBLE=0 -DGBCOMPACT=0 && make -j8 && sudo make install && sudo ldconfig && cd ../..
      - run: git clone --depth 1 --branch master https://github.com/GraphBLAS/LAGraph && cd LAGraph/build && cmake .. && make -j8 && sudo make install && sudo ldconfig && cd ../..
#      - run: python/scripts/run_all_queries.sh
      - run: cpp/scripts/rebuild.sh
      - run: cd cpp/cmake-build-release && ThreadsNum=8 ./sigmod2014pc_cpp
      - slack/status
