version: 2.1
jobs:
  build:
    docker:
      - image: ftsrg/pygraphblas-notebook
    resource_class: xlarge
    steps:
      - checkout
      - run: wget "https://www.dropbox.com/s/sgrwihjji551teq/o1k.zip?dl=1" -O temp.zip && unzip temp.zip -d csvs && rm temp.zip
      - run: python/scripts/run_all_queries.sh
