version: 2.1
jobs:
  build:
    docker:
      - image: ftsrg/pygraphblas-notebook:v3.2.0-fork-v2
    resource_class: xlarge
    steps:
      - checkout
      - restore_cache:
          keys:
            - csvs-{{ checksum "csvs/o1k.sha1" }}
      - run:
          name: Load test data
          command: |
            cd csvs/
            sha1sum -c o1k.sha1 || ( wget "https://www.dropbox.com/s/sgrwihjji551teq/o1k.zip?dl=1" -O temp.zip && unzip -o temp.zip && rm temp.zip && sha1sum -c o1k.sha1 )
      - save_cache:
          key: csvs-{{ checksum "csvs/o1k.sha1" }}
          paths:
            - csvs
      - run: python/scripts/run_all_queries.sh
      - run: cpp/scripts/rebuild.sh
      - run: cd cpp/cmake-build-release && ./sigmod2014pc_cpp
